### PR TITLE
adjust copy plugin test to work on msys Perl

### PR DESCRIPTION
**Pull request by plicease**
For #211

### CODE REVIEW

**Comment by hakonhagland** [comment]
How can I test this PR? I tried:
```
$ git checkout -b graham/msys2 upstream/graham/msys2
Branch 'graham/msys2' set up to track remote branch 'graham/msys2' from 'upstream'.
Switched to a new branch 'graham/msys2'
```
Then I would like to test with `dzil test`, so I ran
```
$ dzil authordeps --missing | cpanm
--> Working on Dist::Zilla::Plugin::Author::Plicease::Thanks
Fetching http://www.cpan.org/authors/id/P/PL/PLICEASE/Dist-Zilla-PluginBundle-Author-Plicease-2.51.tar.gz ... OK
Configuring Dist-Zilla-PluginBundle-Author-Plicease-2.51 ... OK
==> Found dependencies: Dist::Zilla::Plugin::Alien, Dist::Zilla::PluginBundle::Git, Dist::Zilla::Plugin::PodWeaver, Test::Script, Test::Version, Perl::Tidy, Pod::Markdown, Dist::Zilla::Plugin::InsertExample, YAML, Dist::Zilla::Plugin::MinimumPerl, Dist::Zilla::Plugin::ReadmeAnyFromPod, Dist::Zilla::App::Command::aliendeps, Test::Pod::Coverage, PerlX::Maybe, Dist::Zilla::Plugin::CopyFilesFromBuild, Dist::Zilla::Util::CurrentCmd, Dist::Zilla::Plugin::AutoMetaResources, Test::Fixme, Dist::Zilla::Plugin::OurPkgVersion, Dist::Zilla::Plugin::InstallGuide, File::ShareDir::Dist, Dist::Zilla::Plugin::Run::BeforeBuild, Dist::Zilla::Plugin::PkgVersion::Block
--> Working on Dist::Zilla::Plugin::Alien
Fetching http://www.cpan.org/authors/id/Z/ZM/ZMUGHAL/Dist-Zilla-Plugin-Alien-0.023.tar.gz ... OK
Configuring Dist-Zilla-Plugin-Alien-0.023 ... OK
==> Found dependencies: Alien::Base, Path::Class
--> Working on Alien::Base
Fetching http://www.cpan.org/authors/id/P/PL/PLICEASE/Alien-Build-2.26.tar.gz ... OK
Configuring Alien-Build-2.26 ... OK
Building and testing Alien-Build-2.26 ...
```
Seems it is trying to install Alien-Build as a dependency of itself, is it correct? It looks strange to me.

**Comment by Grinnz** [comment]
It's a dependency for authoring, not the dist.

**Comment by plicease** [comment]
@hakonhagland I think using dzil to test this is overkill.  You should be able to use `prove -l` to test the whole suite and `prove -l t/alien_build_plugin_build_copy.t` to test just the test in question.

The Alien dep can and probably should be removed from the dzil bundle tbh, so I'm opening this ticket:
https://github.com/plicease/Dist-Zilla-PluginBundle-Author-Plicease/issues/3

**Comment by plicease** [comment]
@hakonhagland Also note that I realized that I had my logic inverted, and did a force push, so if you test this make sure you are using f15a356

**Comment by hakonhagland** [comment]
@plicease 
> prove -l t/alien_build_plugin_build_copy.t to test just the test in question

Yes that works. The test now passes on my machine. I wonder if [line 22](https://github.com/Perl5-Alien/Alien-Build/blob/master/t/alien_build_plugin_build_copy.t#L22) should also be changed similarly, even if it does not have any effect on the outcome of the test as it is now.

**Comment by hakonhagland** [comment]
@Grinnz 
> It's a dependency for authoring, not the dist
Yes, but still is it reasonable to have a self-dependency for authoring?

**Comment by plicease** [comment]
> Yes, but still is it reasonable to have a self-dependency for authoring?

There isn't anything inherently unreasonable about an authoring self-dependency.  In this case AB is required by the dzil bundle because of long since deprecated interface, so I've removed it from my dzil plugin bundle as of 2.53.

**Pull request merged**
